// <auto-generated />
using ERP.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP.Repositories.Migrations.WorkorderStatus
{
    [DbContext(typeof(WorkorderStatusContext))]
    [Migration("20181122181251_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP.Models.WorkorderStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("WorkorderStatuses");

                    b.HasData(
                        new { ID = 1, Name = "New" },
                        new { ID = 2, Name = "Scheduled" },
                        new { ID = 3, Name = "In Progress" },
                        new { ID = 4, Name = "Completed" },
                        new { ID = 5, Name = "Rejected" },
                        new { ID = 6, Name = "Cancelled" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
