// <auto-generated />
using System;
using ERP.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP.Repositories.Migrations.Material
{
    [DbContext(typeof(MaterialContext))]
    [Migration("20181122214955_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID");

                    b.Property<string>("Details");

                    b.Property<string>("Name");

                    b.Property<float>("QuantityInStock");

                    b.Property<int?>("TypeID");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TypeID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ERP.Models.MaterialCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MaterialCategories");

                    b.HasData(
                        new { ID = 1, Name = "Rod" },
                        new { ID = 2, Name = "Plate" },
                        new { ID = 3, Name = "Sheet" }
                    );
                });

            modelBuilder.Entity("ERP.Models.MaterialType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new { ID = 1, Name = "Aluminum" },
                        new { ID = 2, Name = "Steel" },
                        new { ID = 3, Name = "Nylon" }
                    );
                });

            modelBuilder.Entity("ERP.Models.Material", b =>
                {
                    b.HasOne("ERP.Models.MaterialCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("ERP.Models.MaterialType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");
                });
#pragma warning restore 612, 618
        }
    }
}
