// <auto-generated />
using System;
using ERP.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP.Repositories.Migrations
{
    [DbContext(typeof(WorkorderContext))]
    [Migration("20181123043602_WorkorderMaterials")]
    partial class WorkorderMaterials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID");

                    b.Property<string>("Details");

                    b.Property<string>("Name");

                    b.Property<float>("QuantityInStock");

                    b.Property<int?>("TypeID");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TypeID");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("ERP.Models.MaterialCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MaterialCategory");
                });

            modelBuilder.Entity("ERP.Models.MaterialType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MaterialType");
                });

            modelBuilder.Entity("ERP.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("WebsiteURL");

                    b.HasKey("ID");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("ERP.Models.Workorder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorizedBy");

                    b.Property<string>("ClientEmail");

                    b.Property<string>("ClientName");

                    b.Property<string>("ClientPhoneNumber");

                    b.Property<DateTime>("DateCompleted");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DatePickedUp");

                    b.Property<DateTime>("DateRequiredBy");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EstDeliveryDate");

                    b.Property<decimal>("EstLabourCost");

                    b.Property<decimal>("EstMaterialCost");

                    b.Property<decimal>("EstOtherCost");

                    b.Property<decimal>("EstTotalCost");

                    b.Property<bool>("QuoteRequested");

                    b.Property<int?>("StatusID");

                    b.Property<decimal>("TotalCost");

                    b.Property<decimal>("TotalLabourCost");

                    b.Property<decimal>("TotalMaterialCost");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("Workorders");
                });

            modelBuilder.Entity("ERP.Models.WorkorderMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CostPerUnit");

                    b.Property<int?>("MaterialID");

                    b.Property<float>("QuantityUsed");

                    b.Property<int?>("VendorID");

                    b.Property<int?>("WorkorderID");

                    b.HasKey("ID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("VendorID");

                    b.HasIndex("WorkorderID");

                    b.ToTable("WorkorderMaterials");
                });

            modelBuilder.Entity("ERP.Models.WorkorderStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("WorkorderStatuses");

                    b.HasData(
                        new { ID = 1, Name = "New" },
                        new { ID = 2, Name = "Scheduled" },
                        new { ID = 3, Name = "In Progress" },
                        new { ID = 4, Name = "Completed" },
                        new { ID = 5, Name = "Rejected" },
                        new { ID = 6, Name = "Cancelled" }
                    );
                });

            modelBuilder.Entity("ERP.Models.Material", b =>
                {
                    b.HasOne("ERP.Models.MaterialCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("ERP.Models.MaterialType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");
                });

            modelBuilder.Entity("ERP.Models.Workorder", b =>
                {
                    b.HasOne("ERP.Models.WorkorderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID");
                });

            modelBuilder.Entity("ERP.Models.WorkorderMaterial", b =>
                {
                    b.HasOne("ERP.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID");

                    b.HasOne("ERP.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorID");

                    b.HasOne("ERP.Models.Workorder", "Workorder")
                        .WithMany()
                        .HasForeignKey("WorkorderID");
                });
#pragma warning restore 612, 618
        }
    }
}
