// <auto-generated />
using System;
using ERP.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190225021346_WithWorkflowEngine")]
    partial class WithWorkflowEngine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryID");

                    b.Property<string>("Details");

                    b.Property<string>("Name");

                    b.Property<float>("QuantityInStock");

                    b.Property<int?>("TypeID");

                    b.Property<int?>("UnitOfMeasureId");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TypeID");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ERP.Models.MaterialCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MaterialCategories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Rod"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Plate"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Sheet"
                        });
                });

            modelBuilder.Entity("ERP.Models.MaterialType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Aluminum"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Steel"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Nylon"
                        });
                });

            modelBuilder.Entity("ERP.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasure");
                });

            modelBuilder.Entity("ERP.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("WebsiteURL");

                    b.HasKey("ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("ERP.Models.Workflows.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorHex");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "",
                            Description = "",
                            Name = "New",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "",
                            Description = "",
                            Name = "In review",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "",
                            Description = "",
                            Name = "Scheduled",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "",
                            Description = "",
                            Name = "In progress",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "",
                            Description = "",
                            Name = "Ready for pickup",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "",
                            Description = "",
                            Name = "Closed",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 7,
                            ColorHex = "",
                            Description = "",
                            Name = "Waiting",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 8,
                            ColorHex = "",
                            Description = "",
                            Name = "Cancelled",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 9,
                            ColorHex = "",
                            Description = "",
                            Name = "Rejected",
                            WorkflowId = 1
                        });
                });

            modelBuilder.Entity("ERP.Models.Workflows.Transition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentStateId");

                    b.Property<int>("NextStateId");

                    b.Property<int>("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Transitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStateId = 1,
                            NextStateId = 2,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentStateId = 2,
                            NextStateId = 3,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 3,
                            CurrentStateId = 3,
                            NextStateId = 4,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 4,
                            CurrentStateId = 4,
                            NextStateId = 5,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 5,
                            CurrentStateId = 5,
                            NextStateId = 6,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 6,
                            CurrentStateId = 1,
                            NextStateId = 7,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 7,
                            CurrentStateId = 2,
                            NextStateId = 7,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 8,
                            CurrentStateId = 3,
                            NextStateId = 7,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 9,
                            CurrentStateId = 4,
                            NextStateId = 7,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 10,
                            CurrentStateId = 5,
                            NextStateId = 7,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 11,
                            CurrentStateId = 7,
                            NextStateId = 1,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 12,
                            CurrentStateId = 7,
                            NextStateId = 2,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 13,
                            CurrentStateId = 7,
                            NextStateId = 3,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 14,
                            CurrentStateId = 7,
                            NextStateId = 4,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 15,
                            CurrentStateId = 7,
                            NextStateId = 5,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 16,
                            CurrentStateId = 7,
                            NextStateId = 6,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 17,
                            CurrentStateId = 1,
                            NextStateId = 8,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 18,
                            CurrentStateId = 2,
                            NextStateId = 8,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 19,
                            CurrentStateId = 3,
                            NextStateId = 8,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 20,
                            CurrentStateId = 4,
                            NextStateId = 8,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 21,
                            CurrentStateId = 5,
                            NextStateId = 8,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 22,
                            CurrentStateId = 7,
                            NextStateId = 8,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 23,
                            CurrentStateId = 1,
                            NextStateId = 9,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 24,
                            CurrentStateId = 2,
                            NextStateId = 9,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 25,
                            CurrentStateId = 3,
                            NextStateId = 9,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 26,
                            CurrentStateId = 4,
                            NextStateId = 9,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 27,
                            CurrentStateId = 5,
                            NextStateId = 9,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 28,
                            CurrentStateId = 7,
                            NextStateId = 9,
                            WorkflowId = 1
                        });
                });

            modelBuilder.Entity("ERP.Models.Workflows.TransitionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TransitionId");

                    b.Property<int>("WorkflowActionId");

                    b.Property<int>("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("TransitionActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TransitionId = 1,
                            WorkflowActionId = 1,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 2,
                            TransitionId = 2,
                            WorkflowActionId = 2,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 3,
                            TransitionId = 3,
                            WorkflowActionId = 3,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 4,
                            TransitionId = 4,
                            WorkflowActionId = 4,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 5,
                            TransitionId = 5,
                            WorkflowActionId = 5,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 6,
                            TransitionId = 6,
                            WorkflowActionId = 6,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 7,
                            TransitionId = 7,
                            WorkflowActionId = 6,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 8,
                            TransitionId = 8,
                            WorkflowActionId = 6,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 9,
                            TransitionId = 9,
                            WorkflowActionId = 6,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 10,
                            TransitionId = 10,
                            WorkflowActionId = 6,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 11,
                            TransitionId = 11,
                            WorkflowActionId = 7,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 12,
                            TransitionId = 12,
                            WorkflowActionId = 8,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 13,
                            TransitionId = 13,
                            WorkflowActionId = 9,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 14,
                            TransitionId = 14,
                            WorkflowActionId = 10,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 15,
                            TransitionId = 15,
                            WorkflowActionId = 11,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 16,
                            TransitionId = 16,
                            WorkflowActionId = 5,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 17,
                            TransitionId = 17,
                            WorkflowActionId = 12,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 18,
                            TransitionId = 18,
                            WorkflowActionId = 12,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 19,
                            TransitionId = 19,
                            WorkflowActionId = 12,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 20,
                            TransitionId = 20,
                            WorkflowActionId = 12,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 21,
                            TransitionId = 21,
                            WorkflowActionId = 12,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 22,
                            TransitionId = 22,
                            WorkflowActionId = 12,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 23,
                            TransitionId = 23,
                            WorkflowActionId = 13,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 24,
                            TransitionId = 24,
                            WorkflowActionId = 13,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 25,
                            TransitionId = 25,
                            WorkflowActionId = 13,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 26,
                            TransitionId = 26,
                            WorkflowActionId = 13,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 27,
                            TransitionId = 27,
                            WorkflowActionId = 13,
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 28,
                            TransitionId = 28,
                            WorkflowActionId = 13,
                            WorkflowId = 1
                        });
                });

            modelBuilder.Entity("ERP.Models.Workflows.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Worflows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("ERP.Models.Workflows.WorkflowAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Reviewing",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Accepted",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Begin work",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Finish work",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Finish workorder",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Waiting",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Back to new",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Back to reviewing",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Name = "Back to accepted",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Name = "Back to work",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            Name = "Ready for pickup",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            Name = "Cancel workorder",
                            WorkflowId = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            Name = "Reject workorder",
                            WorkflowId = 1
                        });
                });

            modelBuilder.Entity("ERP.Models.Workorder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorizedBy");

                    b.Property<string>("ClientEmail");

                    b.Property<string>("ClientName");

                    b.Property<string>("ClientPhoneNumber");

                    b.Property<DateTime>("DateCompleted");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DatePickedUp");

                    b.Property<DateTime>("DateRequiredBy");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EstDeliveryDate");

                    b.Property<decimal>("EstLabourCost");

                    b.Property<decimal>("EstMaterialCost");

                    b.Property<decimal>("EstOtherCost");

                    b.Property<decimal>("EstTotalCost");

                    b.Property<bool>("QuoteRequested");

                    b.Property<int?>("StatusID");

                    b.Property<decimal>("TotalCost");

                    b.Property<decimal>("TotalLabourCost");

                    b.Property<decimal>("TotalMaterialCost");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("Workorders");
                });

            modelBuilder.Entity("ERP.Models.WorkorderMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CostPerUnit");

                    b.Property<int?>("MaterialID");

                    b.Property<float>("QuantityUsed");

                    b.Property<int?>("UnitOfMeasureId");

                    b.Property<int?>("VendorID");

                    b.Property<int?>("WorkorderID");

                    b.HasKey("ID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex("VendorID");

                    b.HasIndex("WorkorderID");

                    b.ToTable("WorkorderMaterials");
                });

            modelBuilder.Entity("ERP.Models.WorkorderStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("WorkorderStatuses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "New"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Scheduled"
                        },
                        new
                        {
                            ID = 3,
                            Name = "In Progress"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Completed"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Rejected"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ERP.Models.Material", b =>
                {
                    b.HasOne("ERP.Models.MaterialCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("ERP.Models.MaterialType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");

                    b.HasOne("ERP.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId");
                });

            modelBuilder.Entity("ERP.Models.Workflows.State", b =>
                {
                    b.HasOne("ERP.Models.Workflows.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ERP.Models.Workflows.Transition", b =>
                {
                    b.HasOne("ERP.Models.Workflows.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ERP.Models.Workflows.TransitionAction", b =>
                {
                    b.HasOne("ERP.Models.Workflows.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ERP.Models.Workflows.WorkflowAction", b =>
                {
                    b.HasOne("ERP.Models.Workflows.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ERP.Models.Workorder", b =>
                {
                    b.HasOne("ERP.Models.WorkorderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID");
                });

            modelBuilder.Entity("ERP.Models.WorkorderMaterial", b =>
                {
                    b.HasOne("ERP.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID");

                    b.HasOne("ERP.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId");

                    b.HasOne("ERP.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorID");

                    b.HasOne("ERP.Models.Workorder", "Workorder")
                        .WithMany()
                        .HasForeignKey("WorkorderID");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
